language: node_js
node_js: 
  - "8"
services:
  - mongodb
env:
  - NODE_ENV=test
  - TEST_APP_PORT=3000

cache:
  directories:
    - "node_modules"

script: 
  - npm start &
  - wait-on http://localhost:3000
  - npm test